Proyectores/Controllers/DocentesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyectores.Models;

namespace Proyectores.Controllers
{
    [Authorize]
    public class DocentesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Docentes
        public ActionResult Index()
        {
            
            return View();
        }
        [HttpGet]
        public ActionResult getDocentes()
        {
            List<Docente> lista = db.Docentes.Include(d => d.Departamento).Include(d => d.Especialidad).Where(x=> x.Activo).ToList();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
        // GET: Docentes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Docente docente = db.Docentes.Find(id);
            if (docente == null)
            {
                return HttpNotFound();
            }
            return View(docente);
        }

        // GET: Docentes/Create
        public ActionResult Create(int id=0)
        {
            ViewBag.id_departamento = new SelectList(db.Departamentos, "id_departamento", "nombre");
            ViewBag.id_especialidad = new SelectList(db.Especialidad, "id_especialidad", "nombre");
            if (id == 0)
                return View(new Docente());
            else
            {
                return View(db.Docentes.FirstOrDefault(x=> x.DocenteId == id));
            }
        }

        // POST: Docentes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DocenteId,Nombre,Apellido,Telefono,Email,id_especialidad,id_departamento")] Docente docente)
        {
            if (ModelState.IsValid)
            {
                if(docente.DocenteId == 0)
                {
                    docente.Activo = true;
                    db.Docentes.Add(docente);
                    db.SaveChanges();
                    return Json(new { success = true, message ="Creado Correctamente"}, JsonRequestBehavior.AllowGet);
                }else
                {
                    db.Entry(docente).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Actualizado Correctamente" }, JsonRequestBehavior.AllowGet);
                }
            }
            ViewBag.id_departamento = new SelectList(db.Departamentos, "id_departamento", "nombre", docente.id_departamento);
            ViewBag.id_especialidad = new SelectList(db.Especialidad, "id_especialidad", "nombre", docente.id_especialidad);
            return View(docente);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            int result = 0;
            Docente docente = db.Docentes.Find(id);
            docente.Activo = false;
            db.Entry(docente).State = EntityState.Modified;
            result = db.SaveChanges();
            if (result > 0)
                return Json(new { success = true, message = "Eliminado correctamente" }, JsonRequestBehavior.AllowGet);
            else
                return Json(new {success = false, message="No se ha eliminado el registro" }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyectores/Controllers/DptoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyectores.Models;

namespace Proyectores.Controllers
{
    public class DptoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Dpto
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult getDepartamentos()
        {
            List<Departamento> lista = db.Departamentos.ToList();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult Create(int id = 0)
        {
            if (id == 0)
                return View(new Departamento());
            else
                return View(db.Departamentos.FirstOrDefault(x=> x.id_departamento == id));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include ="id_departamento,nombre,mision,vision,historia,ubicacion,organizacion")]Departamento departamento)
        {
            if(departamento.id_departamento == 0)
            {
                db.Departamentos.Add(departamento);
                db.SaveChanges();
            }else
            {
                db.Entry(departamento).State = EntityState.Modified;
                db.SaveChanges();
            }
            return Json(new {success= true, message="Operacion finalizada" }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            
                Departamento emp = db.Departamentos.Where(x => x.id_departamento == id).FirstOrDefault<Departamento>();
                db.Departamentos.Remove(emp);
                db.SaveChanges();
                return Json(new { success = true, message = "Borrado Completamente" }, JsonRequestBehavior.AllowGet);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyectores/Controllers/MarcasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyectores.Models;

namespace Proyectores.Controllers
{
    public class MarcasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Marcas
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult getMarcas()
        {
            List<Marca> lista = db.Marca.ToList();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }   
        
        [HttpGet]
        public ActionResult Crear(int id = 0)
        {
            if (id == 0)
                return View(new Marca());
            else
            {
                var marca = db.Marca.FirstOrDefault(x => x.id_marca == id);
                return Json(new {success = true, id_marca = marca.id_marca, marca = marca.marca }, JsonRequestBehavior.AllowGet);
            }
        }    
        [HttpPost]
        public ActionResult Crear([Bind(Include ="id_marca, marca")]Marca marca)
        {
            int id = int.Parse(Request.Form["id_marca"]);
            string m = Request.Form["marca"];
            marca = new Marca { id_marca = id, marca = m };
            if (marca.id_marca == 0)
            {
                db.Marca.Add(marca);
                db.SaveChanges();
                return Json(new { success = true, message = "Marca Registrada Correctamente" }, JsonRequestBehavior.AllowGet);
            }else
            {
                db.Entry(marca).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, message = "Marca Actualizada Correctamente" }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            int result = 0;
            var m = db.Marca.FirstOrDefault(x => x.id_marca == id);
            db.Marca.Remove(m);
            result = db.SaveChanges();
            if(result > 0)
                return Json(new { success = true, message = "Marca Eliminada Correctamente" }, JsonRequestBehavior.AllowGet);
            else
                return Json(new { success = false, message = "No se ha eliminado" }, JsonRequestBehavior.AllowGet);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyectores/Controllers/PrestamosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyectores.Models;
using Microsoft.AspNet.Identity;
using System.Globalization;

namespace Proyectores.Controllers
{
    [Authorize]
    public class PrestamosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Prestamos
        public ActionResult Index()
        {
            
            return View();
        }
        
        [HttpGet]
        public JsonResult getPrestamos()
        {
            var prest = from item in db.Prestamos
                        select new {Proyector = item.Proyector.Marca.marca + " "+ item.Proyector.nombre,
                        Docente = item.Docente.Nombre+" " + item.Docente.Apellido,
                        Responsable = item.Responsable.Nombre + " "+ item.Responsable.Apellidos,
                        fecha = item.fecha,
                        activo = item.activo,
                        finalizado = item.finalizado,
                        id_prestamo = item.id_prestamo
                        };

            return Json(new {data = prest }, JsonRequestBehavior.AllowGet);
        }

        // GET: Prestamos/Create
        public ActionResult Create(int? id)
        {

            ViewBag.id_proyector = new SelectList(db.Proyectores, "id_proyector", "nombre");
            ViewBag.id_docente = new SelectList(db.Docentes, "DocenteId", "Nombre");
            if (id==0)
            {
                return View(new Prestamo());
            }else
            {
                var prest = db.Prestamos
                            .Include(p => p.Docente)
                            .Include(p => p.Proyector)
                            .FirstOrDefault(x => x.id_docente == id)
                            ;
                return View(prest);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_prestamo,id_proyector,id_docente,id_responsable,fecha,prestamo_anulado,finalizado,activo")] Prestamo prestamo)
        {
            var userID = User.Identity.GetUserId();
            prestamo.id_responsable = userID;
            string mensaje = "Error en la validación de los datos";
            bool band = false;

            prestamo.Docente = db.Docentes.FirstOrDefault(x => x.DocenteId == prestamo.id_docente);
            prestamo.Responsable = db.Users.FirstOrDefault(x => x.Id == prestamo.id_responsable);
            prestamo.Proyector = db.Proyectores.FirstOrDefault(x => x.id_proyector == prestamo.id_proyector);
            var fecha = Request.Form["fecha"];

            prestamo.fecha = DateTime.ParseExact(fecha, "d", CultureInfo.InvariantCulture);
            if (ModelState.IsValid)
            {

                if (prestamo.id_prestamo == 0)
                {
                    prestamo.activo = true;
                    prestamo.finalizado = false;
                    db.Prestamos.Add(prestamo);
                    db.SaveChanges();
                    mensaje = "Prestamo Guardado Correctamente";
                    band = true;
                }
                else
                {
                    //A la juerza
                    Prestamo tmp = db.Prestamos.Find(prestamo.id_prestamo);
                    tmp.id_proyector = prestamo.id_proyector;
                    tmp.id_responsable = prestamo.id_responsable;
                    tmp.fecha = prestamo.fecha;
                    tmp.activo = prestamo.activo;
                    tmp.Docente = prestamo.Docente;
                    tmp.Responsable = prestamo.Responsable;
                    tmp.id_responsable = User.Identity.GetUserId();
                    db.Entry(tmp).State = EntityState.Modified;
                    db.SaveChanges();
                    //db.Entry(prestamo).State = EntityState.Modified;  Esto genera un error desconocido
                    //db.SaveChanges();
                    mensaje = "Prestamo Actualizado Correctamente";
                    band = true;
                }
            }

            ViewBag.id_proyector = new SelectList(db.Proyectores, "id_proyector", "nombre", prestamo.id_proyector);
            ViewBag.id_docente = new SelectList(db.Docentes, "DocenteId", "Nombre");

            return Json(new { message = mensaje, success = band }, JsonRequestBehavior.AllowGet);
        }

        // GET: Prestamos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestamo prestamo = db.Prestamos.Find(id);
            if (prestamo == null)
            {
                return HttpNotFound();
            }
            return View(prestamo);
        }

        // POST: Prestamos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prestamo prestamo = db.Prestamos.Find(id);
            prestamo.activo = false;
            db.Entry(prestamo).State = EntityState.Modified;
            db.SaveChanges();
            return Json(new { data = "Eliminado Correctamente", success = true }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyectores/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SPP</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/roboto.css" rel="stylesheet" />
    <link href="~/Content/animate.min.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/light-bootstrap-dashboard.css" rel="stylesheet"/>
    <link href="~/Content/pe-icon-7-stroke.css" rel="stylesheet" />
</head>
<body>
    <!--=== Encabezado de la aplicacion ===-->
    <!-- Contenedor para Barra lateral izquierda -->
    <div class="wrapper">
        <!-- Barra lateral -->
        <div class="sidebar" data-color="purple" data-image="/Content/img/marca.png">
            <div class="sidebar-wrapper">
                <!-- Logo de la aplicacion -->
                <div class="logo">
                    <a href="@Url.Action("Index", "Home")" class="simple-text">
                        <i class=""></i> SPP
                    </a>
                </div>
                <!-- Elementos del menu principal -->
                <ul class="nav">

                    <!--usuarios 
                    <li>
                        <a href="@Url.Action("Index", "Usuarios")">
                            <i class="pe-7s-user"></i>
                            <p>Usuarios</p>
                        </a>
                    </li> 
                        -->
                    <!--Docentes-->
                    <li>
                        <a href="@Url.Action("Index","Docentes")">
                            <i class="pe-7s-coffee"></i>
                            <p>Docentes</p>
                        </a>                        
                    </li>
                    <!--DEPARTAMENTOS-->
                    <li>
                        <a href="@Url.Action("Index","Dpto")">
                            <i class="pe-7s-world"></i>
                            <p>Departamentos</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Proyectores")">
                            <i class="pe-7s-display1"></i>
                            <p>Proyectores</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Prestamos")">
                            <i class="pe-7s-notebook"></i>
                            <p>Prestamos</p>
                        </a>
                    </li>

                    <!-- Fondo de barra lateral -->
                    
                </ul>
                
            </div>
        </div>
        
        <!-- Diseniando panel principal -->
        <div class="main-panel">
            <nav class="navbar navbar-default navbar-fixed">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example2">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="#" class="navbar-brand">@ViewBag.Title</a>
                    </div>
                    <!-- Menu superior derecho-->
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                <p>
                                    Elementos rapidos
                                    <b class="caret"></b>
                                </p>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index", "Marcas")">Agregar Marcas</a></li>
                                <li><a href="#">Estados de prestamo</a></li>
                                <li><a href="#">Especialidad Docentes</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Registrar Proyector</a></li>
                                <li><a href="#">Registrar Prestamo</a></li>
                            </ul>
                        </li>
                        <li>
                            
                        </li>
                            @if (Request.IsAuthenticated)
                            {
                              <li>
                                  <a href="@Url.Action("Index", "Manage")">
                                    <p>Hola @User.Identity.GetUserName() !</p>
                                  </a>
                              </li>
                              <li>
                                  <a href="@Url.Action("LogOff", "Account")">
                                      <p>
                                          Cerrar sesión
                                      </p>
                                  </a>
                              </li>
                            }
                        </ul>
                    <!-- Fin del menu superior derecho-->

                </div>
            </nav>
            <div class="content">
                @RenderBody()
            </div>
        </div>
        <!-- Fin del panel principal-->
    </div>
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-notify.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/light-bootstrap-dashboard.js"></script>

    <script src="~/Scripts/notify.min.js"></script>

    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.jqueryui.min.js"></script>
    <script src="~/Scripts/bootstrap-notify.js"></script>
    <script src="~/Scripts/bootstrap-select.js"></script>
    <script>
        function Notificacion(tipo, mensaje, icono) {
            $.notify({
                icon: icono,
                message: mensaje

            },{
                type: tipo,
                timer: 1000,
                placement: {
                    from: "top",
                    align: "center"
                }
            });
        }
    </script>
    @RenderSection("Scripts", required: false)  

</body>
</html>