Proyectores/Controllers/ProyectoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyectores.Models;

namespace Proyectores.Controllers
{
    public class ProyectoresController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Proyectors
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult getProyectores()
        {
            var lista = from item in db.Proyectores
                        where item.activo == true
                        select new {
                            marca = item.Marca.marca,
                            nombre = item.nombre,
                            estado = item.Estado.nombre,
                            id_proyector = item.id_proyector
                        };
            return Json(new {data = lista}, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult Crear(int id = 0)
        {
            ViewBag.lista_marcas = new SelectList(db.Marca.ToList(), "id_marca", "marca");
            ViewBag.lista_estados = new SelectList(db.Estados.ToList(), "id_estado", "nombre");            
            if (id == 0)
                return View(new Proyector());
            else
                return View(db.Proyectores.FirstOrDefault(x => x.id_proyector == id));
        }
        [HttpPost]
        public ActionResult Crear([Bind(Include = "id_proyector,lista_marcas,lista_estados,nombre,activo")]Proyector proyector)
        {
            bool band = false;
            string msj = "";
            try
            {
                int id_marca = int.Parse(Request.Form["lista_marcas"]);
                int id_estado = int.Parse(Request.Form["lista_estados"]);

                if (id_marca > 0 && id_estado > 0)
                {
                    proyector.id_marca = id_marca;
                    proyector.id_estado = id_estado;

                    if (proyector.id_proyector == 0)
                    {
                        if (ModelState.IsValid)
                        {
                            db.Proyectores.Add(proyector);
                            db.SaveChanges();
                            band = true;
                            msj = "Proyector registrado Correctamente";
                        }
                    }
                    else
                    {
                        db.Entry(proyector).State = EntityState.Modified;
                        db.SaveChanges();
                        band = true;
                        msj = "Actualizado correctamente";
                    }
                }
                else
                {
                    throw new Exception("No se ha seleccionado Marca ó Estado de Proyector");
                }
            }
            catch (Exception ex)
            {
                band = false;
                msj = "Error: " + ex.Message;
            }
            return Json(new { success = band, message = msj }, JsonRequestBehavior.AllowGet);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyectores/Views/Proyectores/Crear.cshtml
@model Proyectores.Models.Proyector
@{ 
    Layout = null;
}

@using (Html.BeginForm("Crear", "Proyectores", FormMethod.Post, new {onsubmit = "return SubmitForm(this)" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Proyector</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_proyector)
        <div class="form-group">
            <label class="control-label col-md-2">Marca</label>
            <div class="col-md-10">
                @Html.DropDownList("lista_marcas", null ,new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.id_marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Modelo</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Estado</label>
            <div class="col-md-10">
                @Html.DropDownList("lista_estados", null,  new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Activo</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.activo, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.activo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default btn-fill" />
            </div>
        </div>
    </div>
} 

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyectores/Views/Proyectores/Delete.cshtml
@model Proyectores.Models.Proyector

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Proyector</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estado.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca.marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca.marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.activo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Proyectores/Views/Proyectores/Details.cshtml
@model Proyectores.Models.Proyector

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Proyector</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estado.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca.marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca.marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.activo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_proyector }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Proyectores/Views/Proyectores/Edit.cshtml
@model Proyectores.Models.Proyector

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Proyector</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_proyector)

        <div class="form-group">
            @Html.LabelFor(model => model.id_marca, "id_marca", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_marca", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_estado, "id_estado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_estado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.activo)
                @Html.ValidationMessageFor(model => model.activo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyectores/Views/Proyectores/Index.cshtml
@model IEnumerable<Proyectores.Models.Proyector>

@{
    ViewBag.Title = "Proyectores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    <a href="#" onclick="PopupForm('@Url.Action("Crear","Proyectores")','Nuevo Proyector')">Crear <i class="glyphicon glyphicon-edit"></i></a>
</p>
<table class="table table-hover table-striped table-responsive" id="tableProyectores">
    <thead>
        <tr>
            <th>
                Marca
            </th>
            <th>
                Modelo
            </th>
            <th>
                Estado
            </th>
            <th>Opciones</th>
        </tr>
    </thead>
</table>
@section scripts
{
<script src="~/Scripts/crud.js"></script>
<script>

    var Popup, dataTable;
    //Cargando tabla de proyectores
    $(document).ready(function () {
        dataTable = $("#tableProyectores").DataTable({
            "ajax": {
                "type": "GET",
                "datatype": "JSON",
                "url": "/Proyectores/getProyectores"
            },
            "columns": [
                { "data": "marca" },
                { "data": "nombre" },
                { "data": "estado" },
                {"data": "id_proyector", "render": function (data) {
                    return "<a href='#' onclick=Editar('@Url.Action("Crear","Proyectores")/" + data + "')><i class='fa fa-pencil'></i> Editar </a> |<a href='#' style='margin-left:1px' onclick=Delete('@Url.Action("Delete","Proyectores")/" + data + "')><i class='fa fa-trash'></i> Borrar</a>";
                },
                    "orderable": false,
                    "searcheable": false,
                    "width": "130px"
                }
                
            ],
            "language":
                {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                }
        });

    });
</script>
}